Lagar regler tillsyn
chas-academy/u02-redesign-unit7 pull request #12
Opened 2020-10-15 09:16 UTC by Oskar-Mikael

2020-10-15 12:39 UTC, stenwall commented
@Oskar-Mikael Lägg till `<script>componentLoader();</script>` i slutet på bodyn för att läsa in javascripten ✨  Plus att du gärna få skriva i description vilken issue som denna pull fixar. Annars ser det bra ut!

2020-10-15 12:44 UTC, stenwall requested changes
@Oskar-Mikael Lägg till `<script>componentLoader();</script>` i slutet på bodyn för att läsa in javascripten ✨  Plus att du gärna få skriva i description vilken issue som denna pull fixar. Annars ser det bra ut!

2020-10-15 17:11 UTC, Oskar-Mikael commented
Fixade ändringarna och mergar nu.

2020-10-15 17:12 UTC, merged

2020-10-15 19:28 UTC, stenwall commented
fix #6

2020-10-15 19:29 UTC, stenwall reviewed
fix #6

2020-10-22 12:12 UTC, stenwall reviewed
lgtm